### ISSUE TITLE
Error opening czi file

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#17]
@NicoKiaru @ssgpers

Opening a CZI file, I am getting below error:

Code:
```
AbstractSpimData spimData = BioFormatsConvertFilesToSpimData.getSpimData( openers );
```

Error:
```
Attempts to set opener settings for file format Zeiss CZI
Attempts to set opener settings for file format Zeiss CZI
java.lang.NullPointerException
	at ch.epfl.biop.bdv.bioformats.BioFormatsMetaDataHelper.getSeriesRootTransform(BioFormatsMetaDataHelper.java:236)
	at ch.epfl.biop.bdv.bioformats.BioFormatsMetaDataHelper.getSeriesRootTransform(BioFormatsMetaDataHelper.java:183)
	at ch.epfl.biop.bdv.bioformats.export.spimdata.BioFormatsConvertFilesToSpimData.lambda$null$7(BioFormatsConvertFilesToSpimData.java:223)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at ch.epfl.biop.bdv.bioformats.export.spimdata.BioFormatsConvertFilesToSpimData.lambda$null$8(BioFormatsConvertFilesToSpimData.java:221)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at ch.epfl.biop.bdv.bioformats.export.spimdata.BioFormatsConvertFilesToSpimData.lambda$getSpimDataInstance$9(BioFormatsConvertFilesToSpimData.java:215)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
	at ch.epfl.biop.bdv.bioformats.export.spimdata.BioFormatsConvertFilesToSpimData.getSpimDataInstance(BioFormatsConvertFilesToSpimData.java:212)
	at ch.epfl.biop.bdv.bioformats.export.spimdata.BioFormatsConvertFilesToSpimData.getSpimData(BioFormatsConvertFilesToSpimData.java:259)
	at bdv.BigStitcherInputDataCreator.main(BigStitcherInputDataCreator.java:66)
```

Any ideas? It seemed to have worked for @ssgpers in his jython script.
It could be that I have slightly different versions of everything in my java environment. 
In general I tried to compile the latest versions of bdv-playground and bdv-bioformats.

**Comment by NicoKiaru** [comment]
also the latest of bioformats ? FYI there's an updated bdv playground version today, you may try after. And if it doesn't work, maybe share the file ?

**Comment by tischi** [comment]
It works if, but only if in the constructor of the loader we specify manually this guy:

`.positionReferenceFrameLength( new Length( 1, UNITS.MICROMETER ) );`

But we don't know what this is doing: https://github.com/BIOP/bigdataviewer-bioformats/issues/18

Maybe your code could try to auto-fill this field from some other information?

**Comment by NicoKiaru** [comment]
Ah yes I remember that you need it on the loader. If you look at the ome-xml file with the standard FIJI bioformats importer - then you'll see where it matters.

**Comment by NicoKiaru** [comment]
This will not happen anymore, you'll have a default 1 micron value now : https://github.com/BIOP/bigdataviewer-bioformats/commit/360ced38d46b96ad2b962a0d6adf1fea56de23f5
